"""Validate and reanalyze the public Liu et al. (2026) behavior files."""

from __future__ import annotations

import argparse
import json
import platform
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from fsrl.analysis.pipeline import analyze_episode, save_analysis_report
from fsrl.cli.liu2026 import _source_tree_sha256
from fsrl.data.liu2026_human import (
    audit_liu2026_behavior_csv,
    build_liu2026_human_episode,
)


def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Audit the public Liu 2026 test-choice CSVs and recompute analysis metrics."
    )
    parser.add_argument("csv", nargs="+", type=Path, help="One or more cohort CSV files")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("outputs/liu2026_human_audit"),
    )
    return parser


def main() -> None:
    args = create_parser().parse_args()
    audits = [audit_liu2026_behavior_csv(path) for path in args.csv]
    record = build_liu2026_human_episode(args.csv)
    record.provenance.update(
        {
            "source_tree_sha256": _source_tree_sha256(PROJECT_ROOT),
            "python": platform.python_version(),
            "argv": sys.argv[1:],
        }
    )
    report = analyze_episode(record)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    audit_path = args.output_dir / "data_quality_report.json"
    audit_payload = {
        "intended_grain": "one participant x test block x tested pair choice",
        "cohorts": audits,
        "combined_rows": sum(item["rows"] for item in audits),
        "combined_subjects": sum(item["n_subjects"] for item in audits),
        "safe_for": [
            "test-choice accuracy",
            "within-session pair response consistency",
            "subjective ranking reconstruction",
            "serial-position and symbolic-distance effects",
        ],
        "not_safe_for": [
            "human response-time analysis",
            "human confidence analysis",
            "learning-prefix trajectories",
            "support-order effects",
            "cross-session trait stability",
        ],
        "paper_reproduction": {
            "overall_accuracy": report.test_accuracy,
            "learned_accuracy": report.acc_supervised,
            "unlearned_accuracy": report.acc_unsupervised,
            "uniform_clip_bimodal_pairs_matching_published_count": report.n_pair_bimodal,
            "beta_boundary_sensitivity_bimodal_pairs": report.beta_sensitivity.get(
                "n_pair_bimodal"
            ),
            "self_consistent_wrong": report.n_subjects_self_consistent_wrong,
            "rank_analysis_subjects": report.n_subjects_rank_analysis,
            "subjects_with_consistent_error_80": report.n_subjects_consistent_error_80,
            "distance_effect_slope": report.distance_effect_slope,
        },
        "findings": [
            {
                "severity": "high",
                "finding": "The public release contains no measured RT, confidence, learning order, or learning-phase response.",
                "impact": "Those quantities cannot be used for retrospective human process alignment.",
            },
            {
                "severity": "medium",
                "finding": "The released Fig. 2d beta table excludes eight all-pairs-majority-correct participants, but its boundary handling is undocumented and not generated by one uniform clipping rule; uniform 0.01/0.99 clipping still matches the released 15-pair count.",
                "impact": "Bimodal-pair count and fitted alpha/beta values are method-sensitive and must be reported with a sensitivity analysis.",
            },
            {
                "severity": "high",
                "finding": "The published A..H support coordinates run low-to-high, opposite the repository true_rank convention.",
                "impact": "Treating config support positions as strong-to-weak evaluates a mirrored support graph.",
            },
        ],
    }
    audit_path.write_text(
        json.dumps(audit_payload, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    report_path = save_analysis_report(report, args.output_dir / "analysis")

    print(f"data quality report: {audit_path}")
    print(f"analysis report: {report_path}")
    print(
        "subjects={subjects}, rows={rows}, accuracy={accuracy:.6f}, "
        "learned={learned:.6f}, unlearned={unlearned:.6f}, pair_bimodal={bimodal}".format(
            subjects=audit_payload["combined_subjects"],
            rows=audit_payload["combined_rows"],
            accuracy=report.test_accuracy,
            learned=report.acc_supervised,
            unlearned=report.acc_unsupervised,
            bimodal=report.n_pair_bimodal,
        )
    )
    print("measured RT: no; measured confidence: no; learning order: unavailable")


if __name__ == "__main__":
    main()
