import numpy as np
from scipy import stats

from fsrl.analysis.matrix import pair_key, query_pair_set, supervised_pair_set
from fsrl.episode.types import TestResponse


def rank_positions(true_rank: list[int]) -> dict[int, int]:
    """cue -> 秩位置（0=最强）。"""
    return {cue: idx for idx, cue in enumerate(true_rank)}


def ranking_distance(i: int, j: int, true_rank: list[int]) -> int:
    """真序秩差（symbolic distance）。"""
    pos = rank_positions(true_rank)
    return abs(pos[i] - pos[j])


def build_subject_pair_accuracy(
    responses: list[TestResponse],
    min_subject_acc: float | None = 0.5,
) -> tuple[dict[int, dict[tuple[int, int], float]], list[int]]:
    """
    每个 batch 元素视为一个「被试」，汇总各 pair 准确率。
    """
    buckets: dict[int, dict[tuple[int, int], list[int]]] = {}
    for resp in responses:
        buckets.setdefault(resp.batch_index, {}).setdefault(resp.pair, []).append(
            int(resp.correct)
        )

    subject_acc: dict[int, dict[tuple[int, int], float]] = {}
    for batch, pairs in buckets.items():
        subject_acc[batch] = {p: float(np.mean(vals)) for p, vals in pairs.items()}

    if min_subject_acc is not None and subject_acc:
        kept = []
        for batch, pairs in list(subject_acc.items()):
            if pairs and float(np.mean(list(pairs.values()))) >= min_subject_acc:
                kept.append(batch)
            else:
                del subject_acc[batch]
        return subject_acc, kept
    return subject_acc, list(subject_acc.keys())


def fit_beta_profile(
    values: list[float] | np.ndarray,
    proportion_denominator: int = 10,
    boundary_rule: str = "paper_clip",
) -> dict | None:
    """
    对 [0,1] 上的比例数据做 Beta 分布 MLE 拟合（Liu Fig 2C–D）。
    """
    arr = np.asarray(values, dtype=np.float64)
    if arr.size < 3:
        return None
    denominator = max(int(proportion_denominator), 2)
    if boundary_rule == "paper_clip":
        # A uniform, inspectable rule that reproduces Liu Fig. 2d's 15-pair
        # bimodal count and most released coefficients.  The source table is
        # not fully generated by one documented rule (its ceiling-only 2--8
        # pair corresponds to 0.999 rather than 0.99), so we do not claim exact
        # parameter reproduction and carry a binomial sensitivity analysis.
        arr = np.clip(arr, 0.01, 0.99)
        boundary_metadata = {"boundary_rule": "clip_0.01_0.99"}
    elif boundary_rule == "binomial_midpoint":
        # Treat each accuracy as a proportion based on repeated pair trials.
        arr = (arr * (denominator - 1) + 0.5) / denominator
        boundary_metadata = {
            "boundary_rule": "binomial_midpoint",
            "boundary_transform_denominator": denominator,
        }
    else:
        raise ValueError(f"unknown beta boundary rule: {boundary_rule}")
    try:
        alpha, beta_param, _, _ = stats.beta.fit(arr, floc=0.0, fscale=1.0)
    except Exception:
        return None

    if alpha < 1.0 and beta_param < 1.0:
        profile = "bimodal"
    elif alpha > 1.0 and beta_param < 1.0:
        profile = "high_accuracy"
    elif alpha > 1.0 and beta_param > 1.0:
        profile = "unimodal"
    else:
        profile = "other"

    ks_stat, ks_p = stats.kstest(arr, "beta", args=(alpha, beta_param))
    return {
        "alpha": float(alpha),
        "beta": float(beta_param),
        "profile": profile,
        "n": int(arr.size),
        "mean": float(np.mean(arr)),
        **boundary_metadata,
        "ks_statistic": float(ks_stat),
        "ks_p_value": float(ks_p),
    }


def analyze_pair_level_beta(
    subject_pair_acc: dict[int, dict[tuple[int, int], float]],
    subjects: list[int],
    all_pairs: list[tuple[int, int]],
    proportion_denominator: int = 10,
    boundary_rule: str = "paper_clip",
) -> list[dict]:
    """跨被试 pair 级 Beta 拟合（Hypothesis I, Fig 2D）。"""
    fits = []
    for pair in all_pairs:
        accs = [
            subject_pair_acc[s][pair]
            for s in subjects
            if pair in subject_pair_acc.get(s, {})
        ]
        fit = fit_beta_profile(accs, proportion_denominator, boundary_rule)
        if fit is None:
            continue
        i, j = pair
        fits.append(
            {
                "pair": pair_key(i, j),
                "rank_distance": abs(i - j),
                "subject_accuracies": accs,
                **fit,
            }
        )
    return fits


def analyze_subject_level_beta(
    subject_pair_acc: dict[int, dict[tuple[int, int], float]],
    subjects: list[int],
    proportion_denominator: int = 10,
    boundary_rule: str = "paper_clip",
) -> list[dict]:
    """被试级 accuracy profile 的 Beta 拟合（prereg Hypothesis I）。"""
    fits = []
    for batch in subjects:
        pairs = subject_pair_acc.get(batch, {})
        if len(pairs) < 3:
            continue
        accs = list(pairs.values())
        fit = fit_beta_profile(accs, proportion_denominator, boundary_rule)
        if fit is None:
            continue
        fits.append({"batch_index": int(batch), "n_pairs": len(accs), **fit})
    return fits


def subject_pairwise_response_consistency(
    subject_pairs: dict[tuple[int, int], float]
) -> float:
    """Mean response consistency in either direction for one subject."""
    if not subject_pairs:
        return float("nan")
    vals = [max(acc, 1.0 - acc) for acc in subject_pairs.values()]
    return float(np.mean(vals))


def subject_error_consistency(subject_pairs: dict[tuple[int, int], float]) -> float:
    """Backward-compatible alias; the quantity is not error-specific."""
    return subject_pairwise_response_consistency(subject_pairs)


def analyze_error_consistency(
    subject_pair_acc: dict[int, dict[tuple[int, int], float]],
    subjects: list[int],
    error_threshold: float = 0.8,
) -> tuple[float, int, float, float, int]:
    """群平均错误一致性 + 多种 consistent-error 口径。

    返回：
      - mean_error_consistency: 每对 max(acc, 1-acc) 的均值（Fig 2E 主指标）。
      - n_subjects_consistent_error_80: 至少有一个 pair 错误率 >= threshold 的被试数。
      - consistent_error_pair_ratio: 每被试中错误率 >= threshold 的 pair 比例均值。
      - consistent_pair_ratio_either_way: 每被试中 max(acc, 1-acc) >= threshold 的 pair 比例均值
        （稳定一致，无论对错）。
      - n_subjects_consistent_any: 至少有一个 pair 达到 max(acc, 1-acc) >= threshold 的被试数。
    """
    consistencies = []
    n_consistent_error = 0
    n_consistent_any = 0
    consistent_error_pair_ratios = []
    consistent_pair_ratios_either_way = []
    for batch in subjects:
        pairs = subject_pair_acc.get(batch, {})
        consistencies.append(subject_error_consistency(pairs))
        n_pairs = len(pairs)
        if n_pairs > 0:
            n_err_pairs = sum(1 for acc in pairs.values() if (1.0 - acc) >= error_threshold)
            n_consistent_pairs = sum(
                1 for acc in pairs.values() if max(acc, 1.0 - acc) >= error_threshold
            )
            consistent_error_pair_ratios.append(n_err_pairs / n_pairs)
            consistent_pair_ratios_either_way.append(n_consistent_pairs / n_pairs)
        if any((1.0 - acc) >= error_threshold for acc in pairs.values()):
            n_consistent_error += 1
        if any(max(acc, 1.0 - acc) >= error_threshold for acc in pairs.values()):
            n_consistent_any += 1
    mean_c = float(np.mean(consistencies)) if consistencies else float("nan")
    mean_ratio = (
        float(np.mean(consistent_error_pair_ratios))
        if consistent_error_pair_ratios
        else float("nan")
    )
    mean_ratio_either = (
        float(np.mean(consistent_pair_ratios_either_way))
        if consistent_pair_ratios_either_way
        else float("nan")
    )
    return mean_c, n_consistent_error, mean_ratio, mean_ratio_either, n_consistent_any


def _accuracy_by_serial_position(
    responses: list[TestResponse],
    true_rank: list[int],
    pair_filter: set[tuple[int, int]] | None = None,
) -> dict[int, float]:
    """Fig 1F：按 cue 秩位置的平均准确率（该位置参与的所有 trial）。"""
    pos_map = rank_positions(true_rank)
    nbcues = len(true_rank)
    buckets: dict[int, list[int]] = {p: [] for p in range(nbcues)}
    for resp in responses:
        if pair_filter is not None and resp.pair not in pair_filter:
            continue
        i, j = resp.pair
        buckets[pos_map[i]].append(int(resp.correct))
        buckets[pos_map[j]].append(int(resp.correct))
    return {
        p: float(np.mean(vals)) if vals else float("nan")
        for p, vals in buckets.items()
    }


def _accuracy_by_rank_distance(
    responses: list[TestResponse],
    true_rank: list[int],
    pair_filter: set[tuple[int, int]] | None = None,
) -> dict[int, float]:
    """Fig 1G：按秩差（symbolic distance）的平均准确率。"""
    buckets: dict[int, list[int]] = {}
    for resp in responses:
        if pair_filter is not None and resp.pair not in pair_filter:
            continue
        d = ranking_distance(resp.pair[0], resp.pair[1], true_rank)
        buckets.setdefault(d, []).append(int(resp.correct))
    return {
        d: float(np.mean(vals)) if vals else float("nan") for d, vals in sorted(buckets.items())
    }


def _subject_accuracy_by_position(
    responses: list[TestResponse],
    true_rank: list[int],
    pair_filter: set[tuple[int, int]] | None = None,
) -> dict[int, dict[int, float]]:
    """逐被试按 rank position 汇总准确率，用于重复测量 ANOVA。"""
    pos_map = rank_positions(true_rank)
    nbcues = len(true_rank)
    # subject -> position -> list of correct values
    buckets: dict[int, dict[int, list[int]]] = {}
    for resp in responses:
        if pair_filter is not None and resp.pair not in pair_filter:
            continue
        i, j = resp.pair
        subj = resp.batch_index
        subj_buckets = buckets.setdefault(subj, {p: [] for p in range(nbcues)})
        subj_buckets[pos_map[i]].append(int(resp.correct))
        subj_buckets[pos_map[j]].append(int(resp.correct))

    result: dict[int, dict[int, float]] = {}
    for subj, pos_vals in buckets.items():
        result[subj] = {
            p: (float(np.mean(vals)) if vals else float("nan"))
            for p, vals in pos_vals.items()
        }
    return result


def repeated_measures_anova_one_way(
    subject_by_position: dict[int, dict[int, float]],
) -> tuple[float, float, float]:
    """One-way repeated-measures ANOVA with Greenhouse-Geisser correction."""
    subjects = sorted(subject_by_position.keys())
    if not subjects:
        return float("nan"), float("nan"), float("nan")
    positions = sorted(next(iter(subject_by_position.values())).keys())
    n_subjects = len(subjects)
    n_positions = len(positions)

    data = np.array(
        [[subject_by_position[s][p] for p in positions] for s in subjects],
        dtype=float,
    )
    # 移除含 nan 的被试
    valid_mask = ~np.isnan(data).any(axis=1)
    data = data[valid_mask]
    if data.shape[0] < 2:
        return float("nan"), float("nan"), float("nan")

    n_subjects = data.shape[0]
    grand_mean = float(np.mean(data))
    pos_means = np.mean(data, axis=0)
    subj_means = np.mean(data, axis=1)

    ss_position = n_subjects * float(np.sum((pos_means - grand_mean) ** 2))
    ss_subject = n_positions * float(np.sum((subj_means - grand_mean) ** 2))
    ss_residual = float(np.sum((data - pos_means - subj_means[:, None] + grand_mean) ** 2))

    df_position = n_positions - 1
    df_subject = n_subjects - 1
    df_residual = df_position * df_subject

    ms_position = ss_position / df_position
    ms_residual = ss_residual / df_residual
    f_value = ms_position / ms_residual if ms_residual > 0 else float("nan")

    covariance = np.cov(data, rowvar=False, ddof=1)
    centering = np.eye(n_positions) - np.ones((n_positions, n_positions)) / n_positions
    centered_covariance = centering @ covariance @ centering
    trace = float(np.trace(centered_covariance))
    trace_square = float(np.trace(centered_covariance @ centered_covariance))
    if trace_square > 0:
        epsilon_gg = (trace * trace) / ((n_positions - 1) * trace_square)
        epsilon_gg = float(
            np.clip(epsilon_gg, 1.0 / (n_positions - 1), 1.0)
        )
    else:
        epsilon_gg = 1.0
    corrected_df_position = epsilon_gg * df_position
    corrected_df_residual = epsilon_gg * df_residual
    p_value = (
        float(stats.f.sf(f_value, corrected_df_position, corrected_df_residual))
        if not np.isnan(f_value)
        else float("nan")
    )
    return float(f_value), p_value, epsilon_gg


def distance_regression(
    distance_acc: dict[int, float],
) -> tuple[float, float, float]:
    """对 distance -> accuracy 做线性回归，返回 (slope, intercept, p)。"""
    if len(distance_acc) < 2:
        return float("nan"), float("nan"), float("nan")
    from scipy import stats

    distances = sorted(distance_acc.keys())
    accs = [distance_acc[d] for d in distances]
    slope, intercept, _, p_value, _ = stats.linregress(distances, accs)
    return float(slope), float(intercept), float(p_value)


def subject_level_distance_effect(
    responses: list[TestResponse], true_rank: list[int]
) -> tuple[float, float, int]:
    """Estimate one distance slope per subject, then test slopes against zero."""
    slopes: list[float] = []
    for subject in sorted({response.batch_index for response in responses}):
        subject_responses = [
            response for response in responses if response.batch_index == subject
        ]
        distance_accuracy = _accuracy_by_rank_distance(
            subject_responses, true_rank
        )
        slope, _, _ = distance_regression(distance_accuracy)
        if np.isfinite(slope):
            slopes.append(slope)
    if not slopes:
        return float("nan"), float("nan"), 0
    if len(slopes) == 1:
        p_value = float("nan")
    elif np.isclose(np.std(slopes, ddof=1), 0.0):
        p_value = 0.0 if not np.isclose(np.mean(slopes), 0.0) else 1.0
    else:
        _, p_value = stats.ttest_1samp(slopes, 0.0)
    return float(np.mean(slopes)), float(p_value), len(slopes)


def analyze_liu_behavioral_effects(
    responses: list[TestResponse],
    true_rank: list[int],
    supervision_set,
    query_set,
    min_subject_acc: float | None = 0.5,
) -> dict:
    """Liu 2026：跨被试 Beta、serial position、distance effect。"""
    s_pairs = supervised_pair_set(supervision_set)
    q_pairs = query_pair_set(query_set)
    unsup_pairs = q_pairs - s_pairs
    all_pairs = sorted(q_pairs)

    subject_pair_acc, subjects = build_subject_pair_accuracy(
        responses, min_subject_acc=min_subject_acc
    )

    expected_pair_count = len(all_pairs)
    paper_subjects = [
        subject
        for subject in subjects
        if not (
            len(subject_pair_acc.get(subject, {})) == expected_pair_count
            and all(acc > 0.5 for acc in subject_pair_acc[subject].values())
        )
    ]

    counts: dict[tuple[int, tuple[int, int]], int] = {}
    for response in responses:
        key = (response.batch_index, response.pair)
        counts[key] = counts.get(key, 0) + 1
    proportion_denominator = int(np.median(list(counts.values()))) if counts else 10
    pair_beta = analyze_pair_level_beta(
        subject_pair_acc,
        paper_subjects,
        all_pairs,
        proportion_denominator,
        boundary_rule="paper_clip",
    )
    subject_beta = analyze_subject_level_beta(
        subject_pair_acc,
        paper_subjects,
        proportion_denominator,
        boundary_rule="paper_clip",
    )
    pair_beta_binomial = analyze_pair_level_beta(
        subject_pair_acc,
        paper_subjects,
        all_pairs,
        proportion_denominator,
        boundary_rule="binomial_midpoint",
    )
    (
        mean_ec,
        n_ec80,
        consistent_error_pair_ratio,
        consistent_pair_ratio_either_way,
        n_subjects_consistent_any,
    ) = analyze_error_consistency(subject_pair_acc, paper_subjects)

    n_bimodal = sum(1 for f in pair_beta if f["profile"] == "bimodal")
    n_high = sum(1 for f in pair_beta if f["profile"] == "high_accuracy")
    n_unimodal = sum(1 for f in pair_beta if f["profile"] == "unimodal")
    n_subj_bimodal = sum(1 for f in subject_beta if f["profile"] == "bimodal")

    serial_all = _accuracy_by_serial_position(responses, true_rank)
    serial_s = _accuracy_by_serial_position(responses, true_rank, s_pairs)
    serial_u = _accuracy_by_serial_position(responses, true_rank, unsup_pairs)
    dist_all = _accuracy_by_rank_distance(responses, true_rank)
    dist_s = _accuracy_by_rank_distance(responses, true_rank, s_pairs)
    dist_u = _accuracy_by_rank_distance(responses, true_rank, unsup_pairs)

    # 重复测量 ANOVA（所有被试，不过滤低准确率）
    subj_pos_all = _subject_accuracy_by_position(responses, true_rank)
    anova_f, anova_p, anova_epsilon = repeated_measures_anova_one_way(subj_pos_all)

    dist_slope, dist_p, dist_n = subject_level_distance_effect(
        responses, true_rank
    )

    return {
        "n_subjects": len(subjects),
        "subjects": subjects,
        "serial_position_acc": {
            "all": serial_all,
            "supervised": serial_s,
            "unsupervised": serial_u,
        },
        "distance_acc": {
            "all": dist_all,
            "supervised": dist_s,
            "unsupervised": dist_u,
        },
        "pair_beta_fits": pair_beta,
        "subject_beta_fits": subject_beta,
        "beta_analysis_n_subjects": len(paper_subjects),
        "beta_excluded_all_pairs_majority_correct": len(subjects) - len(paper_subjects),
        "beta_boundary_rule": "uniform_clip_0.01_0.99_matches_published_bimodal_count",
        "beta_sensitivity": {
            "boundary_rule": "binomial_midpoint",
            "n_pair_bimodal": sum(
                1 for fit in pair_beta_binomial if fit["profile"] == "bimodal"
            ),
            "n_pair_high_accuracy": sum(
                1 for fit in pair_beta_binomial if fit["profile"] == "high_accuracy"
            ),
            "n_pair_unimodal": sum(
                1 for fit in pair_beta_binomial if fit["profile"] == "unimodal"
            ),
        },
        "n_pair_bimodal": n_bimodal,
        "n_pair_high_accuracy": n_high,
        "n_pair_unimodal": n_unimodal,
        "n_subject_bimodal": n_subj_bimodal,
        "mean_error_consistency": mean_ec,
        "mean_pairwise_response_consistency": mean_ec,
        "n_subjects_consistent_error_80": n_ec80,
        "consistent_error_pair_ratio": consistent_error_pair_ratio,
        "consistent_pair_ratio_either_way": consistent_pair_ratio_either_way,
        "n_subjects_consistent_any": n_subjects_consistent_any,
        "subject_pair_acc": subject_pair_acc,
        "serial_position_anova_f": anova_f,
        "serial_position_anova_p": anova_p,
        "serial_position_anova_epsilon_gg": anova_epsilon,
        "distance_effect_slope": dist_slope,
        "distance_effect_p": dist_p,
        "distance_effect_n_subjects": dist_n,
    }
